//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Resource.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SMSHome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SMSHome() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMS.Resource.Shared.SMSHome", typeof(SMSHome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Portfolios.
        /// </summary>
        public static string Addmission_Process_Heading {
            get {
                return ResourceManager.GetString("Addmission_Process_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;A&lt;/b&gt;&amp;nbsp;collection of student work samples, student self-assessments, and goal statements that reflect student progress..
        /// </summary>
        public static string Addmission_Process_Paragraph {
            get {
                return ResourceManager.GetString("Addmission_Process_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For new admissions, the Student Management System provides registration.
        /// </summary>
        public static string Announcement_Heading {
            get {
                return ResourceManager.GetString("Announcement_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More...
        /// </summary>
        public static string Banner_Right_Action_LearnMore {
            get {
                return ResourceManager.GetString("Banner_Right_Action_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Learning Center.
        /// </summary>
        public static string Banner_Right_Heading1 {
            get {
                return ResourceManager.GetString("Banner_Right_Heading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Approach to Student Education.
        /// </summary>
        public static string Banner_Right_Heading2 {
            get {
                return ResourceManager.GetString("Banner_Right_Heading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education is the passport to the future, for tomorrow belongs to those who prepare for it today. 
        ///Knowledge is power. Encourage your students to start harnessing that power today..
        /// </summary>
        public static string Banner_Right_Pragraph {
            get {
                return ResourceManager.GetString("Banner_Right_Pragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Button_Subscribe {
            get {
                return ResourceManager.GetString("Button_Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get More..
        /// </summary>
        public static string Cammon_Action_Link {
            get {
                return ResourceManager.GetString("Cammon_Action_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The university offers better courses to students. for 12th, graduation, and masters.
        /// </summary>
        public static string Course_Announcement_Heading {
            get {
                return ResourceManager.GetString("Course_Announcement_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrance exam.
        /// </summary>
        public static string Entrance_Exam_Heading {
            get {
                return ResourceManager.GetString("Entrance_Exam_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More..
        /// </summary>
        public static string Entrance_Exam_Link {
            get {
                return ResourceManager.GetString("Entrance_Exam_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the most important aspects of our college is the entrance exam. For the new admission, it provides questions with multiple answers..
        /// </summary>
        public static string Entrance_Exam_Paragraph {
            get {
                return ResourceManager.GetString("Entrance_Exam_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#169;&amp;nbsp;2023&amp;nbsp;, Student Management System | www.smsbestcareer.com.
        /// </summary>
        public static string Footer_CopyRight_Text {
            get {
                return ResourceManager.GetString("Footer_CopyRight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pl.No : 10 , Alarapur, Near Ranga Bazar,Tankapani Rode,Sai Temple.
        /// </summary>
        public static string Have_a_Questions_Address {
            get {
                return ResourceManager.GetString("Have_a_Questions_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;+91&lt;/span&gt;7299939748.
        /// </summary>
        public static string Have_a_Questions_Contact {
            get {
                return ResourceManager.GetString("Have_a_Questions_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;alokjena135@gmail.com&lt;/span&gt;.
        /// </summary>
        public static string Have_a_Questions_Email {
            get {
                return ResourceManager.GetString("Have_a_Questions_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a Questions?.
        /// </summary>
        public static string Have_a_Questions_Heading {
            get {
                return ResourceManager.GetString("Have_a_Questions_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string Nav_Item1 {
            get {
                return ResourceManager.GetString("Nav_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COURSES.
        /// </summary>
        public static string Nav_Item2 {
            get {
                return ResourceManager.GetString("Nav_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FACULTY.
        /// </summary>
        public static string Nav_Item3 {
            get {
                return ResourceManager.GetString("Nav_Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVENTS.
        /// </summary>
        public static string Nav_Item4 {
            get {
                return ResourceManager.GetString("Nav_Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLASS ROOM.
        /// </summary>
        public static string Nav_Item5 {
            get {
                return ResourceManager.GetString("Nav_Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOG.
        /// </summary>
        public static string Nav_Item6 {
            get {
                return ResourceManager.GetString("Nav_Item6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iAcademy.
        /// </summary>
        public static string Nav_Left_Icon_Text {
            get {
                return ResourceManager.GetString("Nav_Left_Icon_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Nav_Right_Join {
            get {
                return ResourceManager.GetString("Nav_Right_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Nav_Right_Login {
            get {
                return ResourceManager.GetString("Nav_Right_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Nav_Right_Registration {
            get {
                return ResourceManager.GetString("Nav_Right_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Blog.
        /// </summary>
        public static string Recent_Blog_Heading {
            get {
                return ResourceManager.GetString("Recent_Blog_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Collect Student Feedback ?.
        /// </summary>
        public static string Recent_Blog_Link1 {
            get {
                return ResourceManager.GetString("Recent_Blog_Link1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Improve Learning ?.
        /// </summary>
        public static string Recent_Blog_Link2 {
            get {
                return ResourceManager.GetString("Recent_Blog_Link2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Improve Faculty Performance ?.
        /// </summary>
        public static string Recent_Blog_Link3 {
            get {
                return ResourceManager.GetString("Recent_Blog_Link3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Improve Facility ?.
        /// </summary>
        public static string Recent_Blog_Link4 {
            get {
                return ResourceManager.GetString("Recent_Blog_Link4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admission.
        /// </summary>
        public static string Student_Admission_Heading {
            get {
                return ResourceManager.GetString("Student_Admission_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admission is the process by which a student applies to and is approved for entry into the university and for a university qualification..
        /// </summary>
        public static string Student_Admission_Paragraph {
            get {
                return ResourceManager.GetString("Student_Admission_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment.
        /// </summary>
        public static string Student_Assignment_Heading {
            get {
                return ResourceManager.GetString("Student_Assignment_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students are given a practise task as part of their assessment. Students can therefore check his assignment facility here..
        /// </summary>
        public static string Student_Assignment_Paragraph {
            get {
                return ResourceManager.GetString("Student_Assignment_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string Student_Attendance_Heading {
            get {
                return ResourceManager.GetString("Student_Attendance_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option allows you to check the attendance. So just click on &quot;Attendance&quot; to check your attendance..
        /// </summary>
        public static string Student_Attendance_Paragraph {
            get {
                return ResourceManager.GetString("Student_Attendance_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12&lt;sup&gt;th&lt;/sup&gt; Board (CHSE and ICSC) Courses..
        /// </summary>
        public static string Student_Courses_Card_12th_Heading {
            get {
                return ResourceManager.GetString("Student_Courses_Card_12th_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best courses are available at the university for 12&lt;sup&gt;th&lt;/sup&gt; grade students. These courses are applicable to BSC- and CBSC-qualified students..
        /// </summary>
        public static string Student_Courses_Card_12th_Paragraph {
            get {
                return ResourceManager.GetString("Student_Courses_Card_12th_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garduation Courses..
        /// </summary>
        public static string Student_Courses_Card_Graduation_Heading {
            get {
                return ResourceManager.GetString("Student_Courses_Card_Graduation_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make them university graduates for a bright future, so the university provides the best courses for the student, both technical and non-technical courses..
        /// </summary>
        public static string Student_Courses_Card_Graduation_Paragraph {
            get {
                return ResourceManager.GetString("Student_Courses_Card_Graduation_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Graduate.
        /// </summary>
        public static string Student_Courses_Card_PostGraduation_Heading {
            get {
                return ResourceManager.GetString("Student_Courses_Card_PostGraduation_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your university degree is a stepping stone to the sky, where there are no restrictions. Try not to quit moving..
        /// </summary>
        public static string Student_Courses_Card_PostGraduation_Paragraph {
            get {
                return ResourceManager.GetString("Student_Courses_Card_PostGraduation_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Result.
        /// </summary>
        public static string Student_Get_Result_Heading {
            get {
                return ResourceManager.GetString("Student_Get_Result_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Result: The student can use this option to find his semi-star result as per the course and as per the department..
        /// </summary>
        public static string Student_Get_Result_Paragraph {
            get {
                return ResourceManager.GetString("Student_Get_Result_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Card.
        /// </summary>
        public static string Student_ID_Card_Heading {
            get {
                return ResourceManager.GetString("Student_ID_Card_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a unique student ID card by utilising this ID Card Facility choice. Student ID cards enable them to obtain all facilities..
        /// </summary>
        public static string Student_ID_Card_Paragraph {
            get {
                return ResourceManager.GetString("Student_ID_Card_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notoce Board.
        /// </summary>
        public static string Student_Notoce_Board_Heading {
            get {
                return ResourceManager.GetString("Student_Notoce_Board_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For any kind of new information, like event details, exam details, or any other special announcement, check the notice board..
        /// </summary>
        public static string Student_Notoce_Board_Paragraph {
            get {
                return ResourceManager.GetString("Student_Notoce_Board_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More..
        /// </summary>
        public static string Student_Registation_From_Link {
            get {
                return ResourceManager.GetString("Student_Registation_From_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student registration form.
        /// </summary>
        public static string Student_Registration_Form_Heading {
            get {
                return ResourceManager.GetString("Student_Registration_Form_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A college enrollment form is a document that students and parents fill out immediately following admission to a college.Just roll over the SMS app..
        /// </summary>
        public static string Student_Registration_Form_Paragraph {
            get {
                return ResourceManager.GetString("Student_Registration_Form_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Login.
        /// </summary>
        public static string Student_Student_Login_Heading {
            get {
                return ResourceManager.GetString("Student_Student_Login_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site is accessible to all authorised students. with the appropriate user ID and password. Without credentials, access is denied..
        /// </summary>
        public static string Student_Student_Login_Paragraph {
            get {
                return ResourceManager.GetString("Student_Student_Login_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Certificate.
        /// </summary>
        public static string Student_Transfer_Certificate_Heading {
            get {
                return ResourceManager.GetString("Student_Transfer_Certificate_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a document issued by any educational institute to a student when he or she wants to transfer from the institute..
        /// </summary>
        public static string Student_Transfer_Certificate_Paragraph {
            get {
                return ResourceManager.GetString("Student_Transfer_Certificate_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id.
        /// </summary>
        public static string Subscribe_Email_Label {
            get {
                return ResourceManager.GetString("Subscribe_Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe Us!.
        /// </summary>
        public static string Subscribe_Us_Heading {
            get {
                return ResourceManager.GetString("Subscribe_Us_Heading", resourceCulture);
            }
        }
    }
}
