//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Resource.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SMSMasterReg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SMSMasterReg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMS.Resource.Shared.SMSMasterReg", typeof(SMSMasterReg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#169;&amp;nbsp;2023&amp;nbsp;, Student Management System | www.smsbestcareer.com.
        /// </summary>
        public static string Footer_CopyRight_Text {
            get {
                return ResourceManager.GetString("Footer_CopyRight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOG.
        /// </summary>
        public static string Nav_Item_Blog {
            get {
                return ResourceManager.GetString("Nav_Item_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLASS ROOM.
        /// </summary>
        public static string Nav_Item_ClassRoom {
            get {
                return ResourceManager.GetString("Nav_Item_ClassRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COURSES.
        /// </summary>
        public static string Nav_Item_Courses {
            get {
                return ResourceManager.GetString("Nav_Item_Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVENTS.
        /// </summary>
        public static string Nav_Item_Events {
            get {
                return ResourceManager.GetString("Nav_Item_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FACULTY.
        /// </summary>
        public static string Nav_Item_Faculty {
            get {
                return ResourceManager.GetString("Nav_Item_Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string Nav_Item_Home {
            get {
                return ResourceManager.GetString("Nav_Item_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Nav_Right_Join {
            get {
                return ResourceManager.GetString("Nav_Right_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Nav_Right_Login {
            get {
                return ResourceManager.GetString("Nav_Right_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Nav_Right_Registration {
            get {
                return ResourceManager.GetString("Nav_Right_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iAcademy.
        /// </summary>
        public static string Navigation_Left_Icon {
            get {
                return ResourceManager.GetString("Navigation_Left_Icon", resourceCulture);
            }
        }
    }
}
